#ifndef FAT32_STATUS_H_
#define FAT32_STATUS_H_

typedef enum FAT32_Status{
    OK,
    BPB_ERROR,
    FSI_SIGNATURE_ERROR,
    ROOT_SIGNATURE_ERROR,
    MEMORY_ALLOCATION_ERROR,
    FILE_NOT_FOUND,
    MISSED_LAST_CLUSTER,
    FAT_BAD_CLUSTER,
    INCORRECT_FILE_NAME,
    NO_FIRST_SECTOR,
    NO_LAST_SECTOR,
    BOOT_SECTOR_NOT_FOUND,
    SD_READ_ERROR,
    SD_WRITE_ERROR,
    NO_FREE_CLUSTER,

} FAT32_Status;

#endif